# -*- coding: utf-8 -*-
"""Thomas Joseph_DS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DI39cfD_0NaArWapQ78vPAPZ3SCcfUsN

## 1. Complete the following code to find the area of an equilateral triangle. Output should be as displayed
"""

import math
side = float(input("Enter the side of the equilateral triangle: "))
area = ((math.sqrt(3))/4)*pow(side,2)
print('Area of triangle',area)

"""## 2. Write a program to count the number of each characters in a string"""

input_str =input("Enter the string")
input_freq = {}
for i in input_str:
    if i in input_freq:
        input_freq[i] += 1
    else:
        input_freq[i] = 1
print ("Count of all characters"+str(input_freq))

"""## Write a program to find the area and perimeter of a rectangle using functions"""

def AOR(width, height):
    Area = width * height
    Perimeter = 2 * (width + height)
    print("Area of a rectangle is:",Area)
    print("Perimeter of rectangle is:",Perimeter)
width = float(input('Enter the width of a rectangle: '))
height = float(input('Enter the height of a rectangle: '))
AOR(width, height)

"""## 4. Write a program to print the fibonacci series till a specified number"""

limit = int(input("Enter the value of limit: "))
first = 0
second = 1
third = 0
count = 1
print("Fibonacci Series: ", end = " ")
while(count <= limit):
  print(third, end = " ")
  count += 1
  first = second
  second = third
  third = first + second

"""## 5. Complete the following code to find the minimum of 3 number using cinditional statements. Output should be as displayed"""

a,b,c = input("Enter three numbers followed by space : ").split()

print("First number :",a)
print("Second number :",b)
print("Third number :",c)

    print("Entered numbers are equal!!!")

    print(a," is smallest")

    print(b," is smallest")

    print(c," is smallest")

a,b,c = input("Enter three numbers followed by  : ").split()

print("First number :",a)
print("Second number :",b)
print("Third number :",c)
if(a==b==c):
    print("Entered numbers are equal!!!")
elif (a<b and a<c):
      print(a," is smallest")
elif (b<a and b<c):
        print(b," is smallest")
elif(c<a and c<b):
          print(c," is smallest")

"""## 6. Write a program to print star pyramind. The number of rows should be taken as input from the user"""

rows = int(input("Size"))
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print('*', end=' ')
    print('')

"""## 7. Complete the following code to convert hour into seconds. Output should be as displayed"""

def to_seconds(t):
    
    return t
time_in_hours = int(input("Enter HRS"))
print(time_in_hours ," Hour is equal to" ,60*60*to_seconds(time_in_hours) ," Seconds")

"""## 8. Write a program to print multiplication table as below"""

number = int(input("Enter the table to print"))
for i in range(1, 11):
  print(number, 'x', i, '=', number*i)

"""## 9. Write a program to take your 5 favorite food as list and print each as 'I like Biriyani'"""

my_list=['Biriyani','Apple','Orange','Grapes','Porotta']
for i in range(0,5):
  print("I like ",my_list[i])

"""## 10. Find error(s) in the following code(if any) and rewrite code.


"""

x= int(input('Enter value of x:'))
y= int(input('Enter value of y:'))
for i in range (0,10):
  if (x == y):
    print("They are equal")
  else:
      print( "They are unequal")

